server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Seguridad básica
    add_header X-Frame-Options SAMEORIGIN always;
    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;

    # Evita cache para env.js
    location = /env.js {
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
    }

    # env dinámico (sin cache)
    location = /env.template.js {
        expires -1;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
    }

    # SPA fallback
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Gzip
    gzip on;
    gzip_comp_level 6;
    gzip_min_length 1024;
    gzip_types
        text/plain
        text/css
        application/json
        application/javascript
        application/xml
        application/xml+rss
        image/svg+xml;
}
